insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'AC','Acre');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'AL','Alagoas');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'AM','Amazonas');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'AP','Amapá');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'BA','Bahia');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'CE','Ceará');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'DF','Distrito Federal');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'ES','Espirito Santo');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'GO','Goias');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'MA','Maranhão');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'MT','Mato Grosso');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'MS','Mato Grosso do Sul');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'MG','Minas Gerais');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'PA','Pará');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'PB','Paraiba');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'PR','Paraná');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'PE','Pernambuco');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'RJ','Rio de Janeiro');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'RN','Rio grande do Norte');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'RS','Rio Grande do Sul');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'RO','Rondônia');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'RR','Roraima');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'SC','Santa Catarina');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'SP','São Paulo');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'SE','Sergipe');
insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, 'TO','Tocantins');

insert into TB_UF(CD_UF, CD_ABREV_UF, DC_UF) values(UF_SEQ.NEXTVAL, '','');